parameters:
    env(OWL_API_AUTHORIZATION_HEADER): Authorization
    sylius.api.authorization_header: "%env(resolve:OWL_API_AUTHORIZATION_HEADER)%"
    owl.security.api_route: "/api/v2"
      
# sylius_api:
#     filter_eager_loading_extension:
#         restricted_resources:
#             '%sylius.model.product.class%':
#                 operations:
#                     shop_get: ~
        

api_platform:
    enable_profiler: false
    enable_entrypoint: false
    patch_formats:
        json: ['application/merge-patch+json']
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: "%sylius.api.authorization_header%"
                type: header
    exception_to_status:
        SM\SMException: 422
        Owl\Bundle\ApiBundle\Exception\CannotRemoveCurrentlyLoggedInUser: 422
        Owl\Bundle\ApiBundle\Exception\ShippingMethodCannotBeRemoved: 422
        Owl\Bundle\ApiBundle\Exception\OrderNoLongerEligibleForPromotion: 422
        Owl\Bundle\ApiBundle\Exception\ZoneCannotBeRemoved: 422
        Owl\Bundle\ApiBundle\Exception\ProvinceCannotBeRemoved: 422
        Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: 400
    collection:
        pagination:
            client_items_per_page: true
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform']
    enable_swagger_ui: false
    enable_re_doc: false

lexik_jwt_authentication:
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: "%sylius.api.authorization_header%"
